---
- name: Create init.groovy.d/
  file:
    path: '/var/lib/jenkins/init.groovy.d/'
    state: directory
    owner: jenkins

- name: jenkins default users
  template:
    src: basic-security.groovy.j2
    dest: '/var/lib/jenkins/init.groovy.d/basic-security.groovy'
    owner: jenkins
    group: jenkins
    mode: 0775

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted

- name: Wait for Jenkins to start up before proceeding.
  command: >
    curl -D - --silent --max-time 5 http://{{ hostvars[inventory_hostname].ansible_host }}:8080
  args:
    warn: false
  register: result
  until: >
    (result.stdout.find("403 Forbidden") != -1)
    or (result.stdout.find("200 OK") != -1)
    and (result.stdout.find("Please wait while") == -1)
  retries: 60
  delay: 5
  changed_when: false
  check_mode: false
- name: Remove Jenkins security init scripts after first startup.
  file:
    path: '/var/lib/jenkins/init.groovy.d/basic-security.groovy'
    state: absent
